<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10503" started-at="2021-07-04T10:20:09Z" finished-at="2021-07-04T10:20:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10503" started-at="2021-07-04T10:20:09Z" finished-at="2021-07-04T10:20:20Z">
      <class name="tests.RPoolFunctionalityTest">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:tests.RPoolFunctionalityTest@7098b907]" name="setExtent" is-config="true" duration-ms="59" started-at="2021-07-04T15:50:09Z" finished-at="2021-07-04T15:50:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="initializeBrowser()[pri:0, instance:tests.RPoolFunctionalityTest@7098b907]" name="initializeBrowser" is-config="true" duration-ms="1347" started-at="2021-07-04T15:50:09Z" finished-at="2021-07-04T15:50:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBrowser -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.RPoolFunctionalityTest@7098b907]" name="setUp" is-config="true" duration-ms="3934" started-at="2021-07-04T15:50:11Z" depends-on-methods="tests.BaseTest.initializeBrowser" finished-at="2021-07-04T15:50:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="whenUserClicksOnCustomerReview()[pri:0, instance:tests.RPoolFunctionalityTest@7098b907]" name="whenUserClicksOnCustomerReview" duration-ms="4478" started-at="2021-07-04T15:50:15Z" finished-at="2021-07-04T15:50:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.redbus.in/rPool/#reviews] but found [https://www.redbus.in/rPool/#reviewss]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.redbus.in/rPool/#reviews] but found [https://www.redbus.in/rPool/#reviewss]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at tests.RPoolFunctionalityTest.whenUserClicksOnCustomerReview(RPoolFunctionalityTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- whenUserClicksOnCustomerReview -->
        <test-method status="PASS" signature="attachScreenshots(org.testng.ITestResult)[pri:0, instance:tests.RPoolFunctionalityTest@7098b907]" name="attachScreenshots" is-config="true" duration-ms="150" started-at="2021-07-04T15:50:19Z" finished-at="2021-07-04T15:50:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=whenUserClicksOnCustomerReview status=FAILURE method=RPoolFunctionalityTest.whenUserClicksOnCustomerReview()[pri:0, instance:tests.RPoolFunctionalityTest@7098b907] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- attachScreenshots -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:tests.RPoolFunctionalityTest@7098b907]" name="closeBrowser" is-config="true" duration-ms="581" started-at="2021-07-04T15:50:19Z" finished-at="2021-07-04T15:50:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:tests.RPoolFunctionalityTest@7098b907]" name="endReport" is-config="true" duration-ms="177" started-at="2021-07-04T15:50:20Z" finished-at="2021-07-04T15:50:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- tests.RPoolFunctionalityTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
